---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Designing "Good" Research Questions**

- How do we write research questions?

- How do we make them "better"?

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. TBD

<br>

:::



## Baglione (2019) Chapter 2 {background-image="Images/Background-Rally_v2.png" .center}





## Huntington-Klein, N. (2022) Chapter 2 {background-image="Images/Background-Rally_v2.png" .center}




## "Research Questions" {background-image="Images/Background-Rally_v2.png" .center}

**(Huntington-Klein 2022)**

<br>

::: {.r-fit-text}
**What is a research question?**
:::

::: notes

Today's reading is all about helping us see the difference between questions and RESEARCH questions.

- A very important distinction.

<br>

### Per the reading, what is the first key element that distinguishes a "question" from a "research question"?

- (**SLIDE**)

:::



## "Research Questions" {background-image="Images/Background-Rally_v2.png" .center}

**(Huntington-Klein 2022)**

<br>

**A research question:**

1. Can be answered

::: notes

It means that it’s possible for there to be some set of evidence in the world that, if you found it, your question would have a believable answer. 

- The book chapter gives an example: what is the best James Bond movie?

<br>

### Why can't that be answered?

### - What if we collected survey data asking people to rank their favorite Bond movies in order? Wouldn't that do it?

- (That's a measure of "popularity" not "quality"!)

<br>

### Give me some examples of other questions that cannot be answered with empirical data.

<br>

### Everybody clear on the first criteria?

<br>

### What is the second key element that distinguishes a "question" from a "research question"?

- **SLIDE**

:::



## "Research Questions" {background-image="Images/Background-Rally_v2.png" .center}

**(Huntington-Klein 2022)**

<br>

**A research question:**

1. Can be answered

2. Improves our understanding of how the world works.

::: notes

A good research question leads to an answer that will improve your understanding of how the world works.
- It should inform theory in some way.

<br>

### Alright then, what is "theory"?
- (Theory just means that there’s a *why* underpinning your view of the world)

- Theory explains why we think the relationships we see in the world are happening 

<br>

**SLIDE**: You've encountered a TON of theories in your time in poli sci so far
:::



## {background-image="Images/03_1-soldier-British-trench-Western-Front-World-War.webp" .center}

::: notes

Essentially, the entire specialization of International Relations exists to propose and test alternative theories of why wars happen.

- Given that war is a devastating and risky activity, it is a puzzle that states keep starting them!

<br>

Selected IR theories to explain war:

- Neorealism: War is the result of states' worrying about their security

- Institutionalism: War is the result of survival fears overwhelming our institutions of international cooperation 

- Economic liberalism: War should be less likely in a world of interdependent trade and specialization

- and on, and on

<br>

None of these theories can be proven, BUT each makes specific predictions about the world and our research questions can help us set up projects to test them.

- Neorealists might propose a research question like: Does the risk of conflict increase when states invest in purely defensive technologies only? e.g. Do security dilemmas actually exist?

- Institutionalists might propose a research question like: Does UN involvement in a conflict zone shorten wars?

- And economic liberals might propose a research question like: Do states that participate more in international trade specialize in fewer types of goods and services?

<br>

### Does this theory piece make some sense?

:::



## "Research Questions" {background-image="Images/Background-Rally_v2.png" .center}

**(Huntington-Klein 2022)**

<br>

**A research question:**

1. Can be answered

2. Improves our understanding of how the world works.

::: notes

You almost certainly have a million intuitions about how and why the world works like it does.

- Our aim is to design research projects that force us to clarify these assumptions in order to test them with empirical data.

- A good research question helps us begin that process

<br>

I especially like the advice from Huntington-Klein that: "A good test for whether a research question informs theory is to imagine that you find an unexpected result, and then wonder whether it would make you change your understanding of the world."

- If the data shows us that defensive military investments don't lead to war I would certainly hope that neorealists would reconsider their theory

<br>

### Any questions on these two basic requirements of a research question?

<br>

So, all academic projects in quantitative political science are framed as an answer to a research question.

- The question itself MUST be answerable with data and the answer must help us better understand the world (support or lead to revision of a theory).
:::

    
    
## "Research Questions" {background-image="Images/Background-Rally_v2.png" .center}

**(Huntington-Klein 2022)**

<br>

**How Do You Know if You’ve Got a Good One?**

:::: {.columns}
::: {.column width="50%"}
- Consider Potential Results

- Consider Feasibility

- Consider Scale
:::

::: {.column width="50%"}
- Consider Design

- Keep It Simple!
:::
::::

::: notes
Walk me through each of these. 

### What does each criteria mean and how do I use it to make my research question "better"?

- **Consider Potential Results**: "If you can’t say something interesting about your potential results, that probably means your research question and your theory aren’t as closely linked as you think!"

- **Consider Feasibility**: "A research question should be a question that can be answered using the right data, if the right data is available. But is the right data available?"
    - You picked the data project first so this should be done!

- **Consider Scale**: "What kind of resources and time can you dedicate to answering the research question? ... Given the confines of, say, a term paper, you could take some wild swings at that question, but you’re likely to do a much more thorough job answering questions with a lot less complexity."

- **Consider Design**: "So, an important part of evaluating whether you have a workable research question is figuring out if there’s a reasonable research design you can use to answer it. Figuring out whether you do have a reasonable research design is the topic of the rest of this book."

- **Keep It Simple!**: "Answering any research question can be difficult. Don’t make it even harder on yourself by biting off more than you can chew!"

<br>

### Everybody clear on these criteria?

Take a minute to reflect and revise
- Try to revise your question to improve it across these criteria

- You may end up with multiple versions, that's great! Keep them all!

<br>

Ok, let's mix it up again!
- Go around the room and hear all the questions

- Explain to each other how you think your question meets these criteria

- Try to help each other refine/tweak/improve the questions

<br>

Now, take a moment to reflect on the feedback you received and the questions you saw and use that experience to revise your question.
:::



## Evaluating Research Questions {background-image="Images/Background-Rally_v2.png" .center}

1. Fortna, V. P., Lotito, N. J., & Rubin, M. A. (2018). Don’t Bite the Hand that Feeds: Rebel Funding Sources and the Use of Terrorism in Civil Wars

2. Xu, X. (2021). To Repress or to Co‐opt? Authoritarian Control in the Age of Digital Surveillance.

3. Clayton, A., O’Brien, D. Z., & Piscopo, J. M. (2023). Women Grab Back: Exclusion, Policy Threat, and Women’s Political Ambition.

::: notes

Apply these tools to the four research articles from last week: What is the question? Is it a "good" one per these criteria? Strengths AND weaknesses!

:::



## Let's Practice! {background-image="Images/Background-Rally_v2.png" .center}

::: notes

Exercise: Use current events (today's newspapers!) to generate research questions (finding the "scientific angle" in the news). You open a few sites and assign a current event to each group. Groups must brainstorm multiple research questions from their story! Present and discuss each. Help them see how many possible questions underpin every "news event"

:::


