---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

Evaluating the theories from 494

:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. TBD

<br>

SLIDE: Reminder of assignment deadline

:::



## Literature Review {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### Submit a literature review for our class research proposal

::: {.r-fit-text}

- A stand-alone argument paper with bibliography

- Required Minimums: 1,000 words, 12 sources

- Due Oct 4th

:::

::: notes

Don't forget our current deadline (tomorrow!)

<br>

*Canvas Assignment Details*

Submit a complete literature review for our class research proposal.

- A stand-alone argument paper with bibliography
- Required Minimums: 1,000 words, 12 sources
- Remember the guidance in the Baglione book for a good macro structure and the importance of paraphrasing NOT directly quoting your chosen sources.

My Advice: Let's adopt the Baglione suggestion to organize this section from the least to most preferred school. So, the premises (key paragraphs) in the body of your paper should be organized around describing and evaluating each "school of thought." You still need to organize the entire section around your thesis, but the development can happen by school.

<br>

**Questions on the assignment?**

<br>

SLIDE: Theory as part of the research proposal

:::



## PLSC 160: Inquiry in Political Science {background-image="Images/Background-Rally_v2.png"  .center}

<br>

::: {.r-fit-text}

Designing a "good" research proposal requires:

- A compelling research question,

- A foundation in the academic literature, and 

- A clear theoretical story to test
:::

::: notes

The students in Senior Seminar are currently on step 3 (theory) for their projects so we thought it would be a good time to give them some feedback!

<br>

SLIDE: Here's the prompt we gave them

:::



## The Prompt: Theory {background-image="Images/Background-Rally_v2.png"  .center}

::: {.r-fit-text}

1. What is your research question?

2. What is your answer to the question? 

3. Explain the reasoning behind your answer

:::

::: notes

This is the assignment prompt Dr. Ponder gave his students

- Our job today will be to review and evaluate those details then to provide feedback to those students

- My hope is that for each question we can give them something useful in terms of what we like and what needs clarification or revising

:::



## Science Requires Theory {background-image="Images/Background-Rally_v2.png" .center}

<br>

"A theory is a set of propositions and concepts that combine to explain phenomena by specifying the relationships among the propositions. Theory's ultimate goal is to predict phenomena" (Mingst and Arreguin-Toft 2017, 72).

<br>

A useful theory, like a useful map, must:

- Be clearly specified

- Be built from logical assumptions, and 

- Accurately explain important outcomes in the world

::: notes

As we discussed on Tuesday, theories are the stories we tell to explain why things happen in the world

- Like maps, neither true nor false, but instead useful or not

<br>

**Any questions on the material we explored last class?**

<br>

*Split class into groups, one per proposal*

<br>

Groups, your job today is to clarify, evaluate and possibly strengthen your assigned model

- Work directly on the board

- FIRST, try to unpack their submission to get a DAG and list of assumptions on the board

<br>

*PRESENT each*

<br>

Now let's focus on feedback

- What could be clearer? 

- Do the premises connect in a logical way?

- Do we have suggestions for revision?

<br>

*PRESENT each*

<br>

Groups, email me your work from today and I'll provide it to each student in 494

<br>

SLIDE: Next class

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### Diagramming a Theory from the AB

::: {.fragment}

::: {.r-fit-text}
1. APA paper citation

2. Describe the DAG

3. Describe the theory 
    
    - e.g. list and explain the assumptions
:::

:::

::: notes

For next class we will divy out the papers on our class AB (using the shared Google Doc) and you will be tasked with diagramming and evaluating the theoretical model in the paper.

<br>

*Divy out the papers from the class AB*

- *Have students put their name next to the article they are claiming*

<br>

REVEAL: Submit to Canvas...

:::