---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Writing your version of our class research project**

- Introduction, Lit Review and Theory

:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. TBD

<br>

Today I want to talk about the proposal you will be submitting at the end of next week.

- SLIDE: Let's connect the dots!

:::



## PLSC 160: Inquiry in Political Science {background-image="Images/Background-Rally_v2.png"  .center}

<br>

::: {.r-fit-text}

Designing a "good" research proposal requires:

- A compelling research question,

- A foundation in the academic literature, and 

- A clear theoretical story to test
:::

::: notes

Big picture aims of this class

<br>

Our job is to learn to produce a "good" research proposal and we have spent the last eight weeks collaborating on a new proposal

- It's time to get this thing completed and down on paper!

:::



## Research Proposal: The Sections {background-image="Images/Background-Rally_v2.png" .center}

::: {.incremental}
1. Introduction: We have a puzzle!

    - Introduce the RQ and make an argument that answering it is important

2. Literature Review: What do we know?

    - Organize and evaluate the relevant academic literature while making an argument about the "best" approach for your project

3. Theory: My proposed answer

    - Explain your answer using a DAG, the key assumptions in your model, and the hypotheses you plan to test
:::

::: notes

At an intuitive level your research proposal does three things and we execute each of those with a series of specific tasks

- REVEAL x 6

<br>

**Questions on this?**

<br>

- Each section should be written as a complete argument that connects to the next one (organized to advance a thesis, with clear macro and meso structures)

- Be sure to consult the "Submission Requirements for the Argument Papers" in the syllabus

- Proposal is due at the end of next week (Oct 25)

<br>

SLIDE: Medium-term target!

:::



## For Next Class: Writing Workshop {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

Before class you must submit to canvas **a completed rough draft** of your research proposal

- All three sections are included 

- EACH has a recognizable macro and meso structure

- Built using paragraphs not bullet points

- Includes a bibliography

::: notes

After the break we will have an in class writing workshop

<br>

To get ready for that I want completed rough drafts submitted before class next Tuesday

- **Questions on the assignment?**

<br>

SLIDE: Today we focus on Section 1

:::




## The Introduction {background-image="Images/Background-Rally_v2.png" .center}

<br>

We have a puzzle!

1. Introduce the research question, and 

2. Make an argument that answering it is important

<br>

::: {.r-fit-text}
**Brainstorm premises in the importance argument**
:::

::: notes

Let's work for a bit on the introduction argument

- You have the research question, so your next job is to outline the importance argument

<br>

Everybody take 10-15 minutes to brainstorm a list of reasons this is an important question

- Aim for a much longer list then you'll need, e.g. 10 reasons!

<br>

*Check in with class, how close is everyone to 10 minimum?*

- *Send them back to work (5 mins), brainstorm more! Push yourself to think of new ways to approach this argument*

<br>

Now, go see how what other people put on their lists!

- Go read them all!

<br>

Come back to your list and reflect on it.

- What are the three strongest, distinct premises on the list?

- Consider that some overlapping items may be consolidated!

- Go!

<br>

SLIDE: Evidence time

:::



## The Introduction {background-image="Images/Background-Rally_v2.png" .center}

<br>

We have a puzzle!

1. Introduce the research question, and 

2. Make an argument that answering it is important

<br>

### Find at least TWO pieces of evidence to support each of your chosen premises

::: notes

Now take some time to find at least TWO piece of evidence to support each of your chosen premises

<br>

Once you have the evidence, start writing!

- Let's get this thing done!

<br>

SLIDE: For next class

:::








