---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Writing your version of our class research project**

- Writing Workshop

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Review canvas submissions

<br>

Today we wrap up our work on the first research proposal

- SLIDE: But first, the big picture aims!

:::



## PLSC 160: Inquiry in Political Science {background-image="Images/Background-Rally_v2.png"  .center}

<br>

::: {.r-fit-text}

Designing a "good" research proposal requires:

- A compelling research question,

- A foundation in the academic literature, and 

- A clear theoretical story to test
:::

::: notes

Big picture aims of this class.

:::



## Research Proposal: The Sections {background-image="Images/Background-Rally_v2.png" .center}

1. Introduction: We have a puzzle!

    - Introduce the RQ and make an argument that answering it is important

2. Literature Review: What do we know?

    - Organize and evaluate the relevant academic literature while making an argument about the "best" approach for your project

3. Theory: My proposed answer

    - Explain your answer using a DAG, the key assumptions in your model, and the hypotheses you plan to test

::: notes

Your research proposal should include three sections, each of which advances an argument

- **Any questions on the assignment?**

<br>

Let's exchange rough drafts and get/give feedback!

- Go!

<br>

*Before class ends, assignment for Thursday!*

<br>

To wrap up our semester, each of you will now design a new research proposal on your own!

- We'll step through building it together, but now we need ideas to kick us off

- SLIDE

:::



## Brainstorming New Projects {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

Find a news story illustrating a type of event or puzzle you find intriguing and may use to develop your research proposal. 

1. Submit an APA citation to your evidence, and

2. An explanation of what specifically you are intrigued by in this example/case

::: notes

For next class, let's all brainstorm some new ideas for real world puzzles to explore

- **Any questions on the assignment for Thursday?**

:::








