---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Designing a Research Proposal**

- Reviewing the literature reviews in your AB

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2026)
:::

::: notes
Prep for Class

1. Review Canvas submissions

2. Flag really good submissions so you can direct students to them

    - i. three clear, separate sentences
    - ii. Each answer is specific (not just named schools but with explanations of what they mean)

<br>

Let's keep working towards developing your literature review

- To start, let's define our term

- **What is a literature review and what role does it play in your research proposal?**

- (**SLIDE**)

:::



## The Literature Review {background-image="Images/Background-Rally_v2.png" .center}

<br>

An argument paper version of your AB that:

::: {.incremental}

1. Makes a **convincing argument** your project builds on the academic literature in useful ways

2. **Organizes AND analyzes** the state of our knowledge on your question

3. Ends by **connecting** the literature to the theory section of your paper

:::

::: notes

**REVEAL x 3**

<br>

Big picture the literature review is an argument paper version of your annotated bibliography that serves as a bridge between the introduction and the theory sections

<br>

**Questions on these aims?**

<br>

Let's move from the big picture to more detail

- **SLIDE**: Baglione gives a set of four fundamentals we can use to make sure our lit review is hitting all the right elements

:::



## Baglione (2019) Chapter 4 {background-image="Images/Background-Rally_v2.png" .center}

<br>

**The Fundamentals of the Literature Review**

1. What are the relevant schools?
2. How does each answer the question?
3. Strengths and weaknesses of each school?
4. Which is "best" for your project?

::: notes

This is not how we necessarily organize the LR, but it is a series of questions the reader of your LR should be able to answer

- **Make sense?**

<br>

**SLIDE**: Now let's zoom all the way in on the detail

:::




## {background-image="Images/Background-Rally_v2.png" .center}

**Introduction**

- Question: What are the competing answers to your RQ in the academic literature?

- Thesis: Your proposal builds on the academic literature

**Premise 1: Explain AND analyze School 1**

**Premise 2: Explain AND analyze School 2**

**Premise 3: Explain AND analyze School 3**

**Conclusion**

- Wrap it up and identify the path forward (e.g. your proposal will focus on School X because...)

::: notes

NEXT WEEK, so NOT YET, this is the outline you will be producing

- This is what you are working torwards producing

<br>

**Questions on the structure of the LR paper as I am assigning it?**

<br>

**SLIDE**: Ok, let's discuss your work for today

:::



## For Today {background-image="Images/Background-Rally_v2.png" .center}

<br>

**Identify and Evaluate the LR Structures in your Bibliography**

1. How is each article's LR organized (e.g. "schools")?

2. What are the strengths of this school?

3. What are the weaknesses of this school?

::: notes

For today, each of you reviewed and evaluated the literature reviews in the articles in your bibliography

<br>

*Point students to the really strong submissions*

I want to make sure everyone is exposed to LOTS of different ways of organizing schools of thought in a research paper

- I also want to highlight submissions that did a really nice job providing useful and specific details

- Go review...

<br>

Go back to your submission for today

- Can you make yours look more like the models?

- e.g. three distinct sentences, each with specific details

<br>

Ok, let's touch base on your work

**Did anybody have a political science research article with no LR?** 

- (If yes, let's check! It might be folded into the theory section)
    
- Alternatively, that can be a sign that that article isn't as helpful for your project as you thought!

<br>

**What were the most common types of "schools" across your articles?** 
    
- (e.g. ways of grouping the answers, think of the list from last class of ways to generate schools)

<br>

**Which approaches to the LR did you find the easiest to read and understand?**

- Share examples and explain what they did that made it so accessible to you.

<br>

**SLIDE**: Next job

:::




## {background-image="Images/Background-Rally_v2.png" .center}

::: {.r-fit-text}

**Brainstorming Schools of Thought**

:::

::: {.incremental}

1. Create a NEW document

2. Write your RQ across the top

3. List all of the "schools" you found in your AB including:

    - A clear label for the school, and
    
    - A complete sentence explanation of what the common elements are in this school
    
:::

::: notes

Next task, make a new document and use it to compile a list of all the different schools of thought you identified

- Make sure each school is named (e.g. give it a clear label) and explained (e.g. what unifies the articles in this school?)

<br>

Share your new document with everyone else and get their feedback

- If you had to pick from each others' lists, what would you pick and why?

- Go!

<br>

**SLIDE**: Assignment for next class

:::




## For Next Class {background-image="Images/Background-Rally_v2.png" .center}

<br>

::: {.r-fit-text}

**The Fundamentals of YOUR Literature Review**

- Name, explain and analyze your schools of thought

- Introduce your thesis for the LR

- Details on Canvas

:::

::: notes

Everybody open up the assignment on Canvas and review the details

- **Questions on the assignment?**

<br>

Canvas ASSIGNMENT: The Fundamentals of your Literature Review

1. What are the relevant schools you have developed for your literature review? (you must have a MINIMUM of two schools of thought)

2. For EACH school:
  	i. How does this group answer your research question? What makes this a coherent "school of thought"?
	  ii. What are the strengths of this school? (minimum three complete ideas)
	  iii. What are the weaknesses of this school? (minimum three complete ideas)

3. Explain the bottom line thesis of your LR: Which school of thought is "best" for your project moving forward? (3+ sentences)


:::