---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Designing an individual research project**

- Finding the possible "Schools of Thought"

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Review Canvas submissions

<br>

SLIDE: Our work last week
:::



## Developing your Research Proposal {background-image="Images/Background-Rally_v2.png" .center}

<br>

### Section 1: The Introduction

- Make an argument that answering your research question is important

<br>

### Outline

- A "good" research question

- A three premise importance argument with evidence

::: notes

At this point everyone should have a good outline of Section 1 of their proposal

- Please try to remember that the premises in your importance argument should not be answers to your RQ

- The importance argument is an argument that we need answers to the question, not that we have them already

<br>

**Questions on Section 1 or our work last week?**

<br>

SLIDE: Now we shift to Section 2, the Literature Review

:::




## Developing your Research Proposal {background-image="Images/Background-Rally_v2.png" .center}

<br>

### Section 2: The Literature Review

- What are the current answers to your RQ?

**Baglione's "Fundamentals" of the Literature Review**

1. What are the relevant schools?
2. How does each answer the question?
3. Strengths and weaknesses of each school?
4. Which is "best" for your project?

::: notes

Your work today in class is building up to writing this section of your proposal

- Section 2 is where you get to discuss the high quality answers to your research question that already exist!

<br>

To do this, today I want each of you to consider the literature reviews in the three articles you brought to class

- Each article should have covered and organized the established literature into "schools of thought"

- Rather than reinvent the proverbial wheel, I want you to consider the options presented in these published articles

- Your goal is to decide on the three "schools of thought" you will use in your proposal

<br>

**Any big picture questions on Section 2?**

<br>

SLIDE: Let's build to this...

:::



## {background-image="Images/Background-Rally_v2.png" .center}

::: {.r-fit-text}
**Section 2: The Literature Review**
:::

<br>

Identify ALL the schools of thought discussed in the literature reviews of your three journal articles

<br>

**For each school:**

1. What does the article name this "school"?

2. Explain the school's answer to your RQ

3. List the articles/books discussed in that school

::: notes

*Read slide*

<br>

Here's the plan

- 45 minutes to diagram the options

- 15 minutes to share what you've found

- 15 minutes to reflect and choose the three "schools" you will focus on in this proposal

<br>

**Any questions?**

- Go!

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### Gathering the Literature

- Submit APA citations for **TWO** relevant and recent political science journal articles for **EACH** of your selected "schools of thought"

- To include an article in your list you MUST have access to the pdf

::: notes

This means you are adding six new articles to the three you already have from today

- That's nine total articles by next class

<br>

**Any questions on the assignment?**

:::














