---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Designing an individual research project**

- Evaluating your second "school of thought"

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Review Canvas submissions

<br>

SLIDE: Let's keep pushing forward in our work!

:::



## Developing your Research Proposal {background-image="Images/Background-Rally_v2.png" .center}

<br>

### Section 2: The Literature Review

- What are the current answers to your RQ?

<br>

### The Fundamentals of the Literature Review

1. What are the relevant schools?
2. How does each answer the question?
3. Strengths and weaknesses of each school?
4. Which is "best" for your project?

::: notes

For today everyone completed their evaluations of the second school of thought from the bibliography

- Let's review your evaluations in pairs

<br>

PAIRS (10 mins)

- Take a few minutes to review and give feedback on the strengths/weaknesses submitted by the other person to Canvas today

- I know you aren't familiar with the specific articles analyzed by the other person, BUT their strengths and weaknesses should be clear enough to understand without that familiarity!

- Go!

:::



## Developing your Research Proposal {background-image="Images/Background-Rally_v2.png" .center}

<br>

### Section 3: Theory

- My proposed answer to the RQ

<br>

### Explain your answer using:

- A DAG

- The assumptions underpinning your causal arrow

- At least two testable hypotheses

::: notes

Ok, just like last class, let's now shift your focus to the theory sections of the papers in your second school of thought

- Specifically, I want you to diagram the DAGs and assumptions for each of the four articles in the second school of thought

<br>

**Questions on what I'm asking you to do?**

- Get to it!

<br>

*15 minutes left*

Let's share something you've learned today!

- Everybody put ONE of the DAGs and models you diagrammed today on the board

- *PRESENT and DISCUSS each*

<br>

For next class we do this exercise one last time but focused on the third school of thought

- Focus on evaluating the strengths and weaknesses of the third school

:::