---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Designing an individual research project**

- Outlining your Literature Review

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. TBD

<br>


:::



## Developing your Research Proposal {background-image="Images/Background-Rally_v2.png" .center}

<br>

### Section 2: The Literature Review

- What are the current answers to your RQ?

<br>

### The Fundamentals of the Literature Review

1. What are the relevant schools?
2. How does each answer the question?
3. Strengths and weaknesses of each school?
4. Which is "best" for your project?

::: notes

Over the last two weeks we have gathered and evaluated a sample of the academic literature that has tried to answer your research question

- Your job for today is to complete your outline of the Lit Review section of your paper

- Outline must be submitted BEFORE class ends

<br>

**Any questions before we dive in?**

- Let's get to work!

<br>

*BEFORE class ENDS*

- SLIDE: Goals for next class

:::



## By the END of Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### Section 3: Theory

- My proposed answer to the RQ

<br>

### Explain your answer using:

- A DAG

- The assumptions underpinning your causal arrow

- At least two testable hypotheses

::: notes

By the **END** of the next class you will submit an outline of the theory section of your proposal. 

- The outline must clearly include these three things

<br>

**Any questions on the assignment?**

:::


