---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Designing an individual research project**

- Outlining your Theory Section

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. TBD

<br>

SLIDE: Let's work on getting these theory outlines done!
:::



## Developing your Research Proposal {background-image="Images/Background-Rally_v2.png" .center}

<br>

### Section 3: Theory

- My proposed answer to the RQ

<br>

### Explain your answer using:

- A DAG

- The assumptions underpinning your causal arrow

- At least two testable hypotheses

::: notes

Your job for today is to complete your outline of the theory section of your paper

- Outline must be submitted BEFORE class ends

<br>

**Any questions before we dive in?**

- Let's get to work!

<br>

*BEFORE class ENDS*

- SLIDE: Goals for next class

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### Submit a completed outline of your final proposal

- All key elements must be included

- Bullet points as complete sentences

- Bibliography and in-text citations in APA

::: notes

**Any questions on the assignment?**

:::


