---
format: revealjs
---

## Today's Agenda {background-image="Images/Background-Rally_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Designing an individual research project**

- Reviewing outlines and writing the final proposal

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Review Canvas submissions

<br>

SLIDE: Big picture wrap-up
:::



## PLSC 160: Inquiry in Political Science {background-image="Images/Background-Rally_v2.png"  .center}

<br>

::: {.r-fit-text}

Designing a "good" research proposal requires:

- A compelling research question,

- A foundation in the academic literature, and 

- A clear theoretical story to test
:::

::: notes

Big picture aims for the class

:::



## Research Proposal: The Sections {background-image="Images/Background-Rally_v2.png" .center}

1. Introduction: We have a puzzle!

    - Introduce the RQ and make an argument that answering it is important

2. Literature Review: What do we know?

    - Organize and evaluate the relevant academic literature while making an argument about the "best" approach for your project

3. Theory: My proposed answer

    - Explain your answer using a DAG, the key assumptions in your model, and the hypotheses you plan to test

::: notes

Your final research proposal should mirror the class proposal you did at midterm

- Three sections, each of which advances an argument

- **Any questions on the assignment?**

<br>

I'll work through the outlines you submitted on Canvas

<br>

Your plan for today

1. PAIRS: Get and give feedback on your outlines

2. Writing workshop!


:::

